
version: '3.2'
services:
  zk1:
    container_name: zk1
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181/kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_DEFAULT_REPLICATION_FACTOR: '1'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_NUM_PARTITIONS: '3'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafkamanager:
    image: giabar/gb-kafkamanager
    ports:
      - 9001:9000
    environment:
      ZK_HOSTS: zk1:2181/kafka

  kafdrop:
    container_name: kafka-drop
    image: thomsch98/kafdrop:latest
    environment:
      LISTEN: '9101'
      ZK_HOSTS: zk1:2181/kafka
    ports:
     - 9101:9101
   